import { Business, Supplier } from "@/types"

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "1",
    name: "Al-Barakah Food Co.",
    nameTh: "บริษัท อัล-บารอกะห์ ฟู้ด จำกัด",
    description: "ผู้ผลิตและจำหน่ายอาหารฮาลาลครบวงจร มุ่งเน้นคุณภาพและมาตรฐาน CICOT",
    province: "สงขลา",
    region: "ภาคใต้",
    industry: "อาหารและเครื่องดื่ม",
    website: "https://example.com",
    review: {
      hasPrayerRoom: true,
      hasHalalFood: true,
      hasFridayFlexibility: true,
      noAlcoholEvents: true,
      noImmodestDressCode: true,
    },
    tier: "gold",
    halalCert: "CICOT",
    seekingInvestment: true,
    investmentType: "musharakah",
    investmentAmount: "5,000,000 บาท",
    createdAt: "2025-01-15",
  },
  {
    id: "2",
    name: "Nusantara Trading",
    nameTh: "นูซันตารา เทรดดิ้ง",
    description: "นำเข้าและกระจายสินค้าฮาลาลจากอาเซียน",
    province: "กรุงเทพมหานคร",
    region: "ภาคกลาง",
    industry: "นำเข้า-ส่งออก",
    review: {
      hasPrayerRoom: true,
      hasHalalFood: true,
      hasFridayFlexibility: true,
      noAlcoholEvents: false,
      noImmodestDressCode: true,
    },
    tier: "silver",
    seekingInvestment: false,
    createdAt: "2025-02-01",
  },
  {
    id: "3",
    name: "Halal Bite Café",
    nameTh: "ฮาลาล ไบท์ คาเฟ่",
    description: "ร้านอาหารและคาเฟ่ฮาลาลใจกลางเมือง ยืนยันฮาลาล 100%",
    province: "ปัตตานี",
    region: "ภาคใต้",
    industry: "ร้านอาหาร",
    review: {
      hasPrayerRoom: false,
      hasHalalFood: true,
      hasFridayFlexibility: true,
      noAlcoholEvents: true,
      noImmodestDressCode: false,
    },
    tier: "bronze",
    seekingInvestment: true,
    investmentType: "mudharabah",
    investmentAmount: "500,000 บาท",
    createdAt: "2025-02-20",
  },
]

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "s1",
    name: "Southern Halal Meat",
    nameTh: "เซาเทิร์น ฮาลาล มีท",
    description: "ผู้ผลิตเนื้อฮาลาลรับรองมาตรฐาน CICOT ส่งทั่วภาคใต้",
    province: "สงขลา",
    region: "ภาคใต้",
    categoryIds: ["meat-poultry", "frozen-food"],
    moqMin: "50",
    moqUnit: "กิโลกรัม/ออเดอร์",
    certificationBody: "CICOT",
    halalCertNumber: "CICOT-2024-1234",
    verified: true,
    createdAt: "2025-01-10",
  },
  {
    id: "s2",
    name: "EcoPackThai",
    nameTh: "อีโคแพ็คไทย",
    description: "บรรจุภัณฑ์รักษ์โลก ไม่ใช้วัสดุต้องห้ามในอิสลาม",
    province: "กรุงเทพมหานคร",
    region: "ภาคกลาง",
    categoryIds: ["eco-packaging", "plastic-packaging", "labels-printing"],
    moqMin: "500",
    moqUnit: "ชิ้น/ออเดอร์",
    verified: true,
    createdAt: "2025-01-20",
  },
  {
    id: "s3",
    name: "Spice Garden",
    nameTh: "สไปซ์ การ์เดน",
    description: "เครื่องเทศและสมุนไพรธรรมชาติ ปลอดสารกำจัดแมลง",
    province: "นครศรีธรรมราช",
    region: "ภาคใต้",
    categoryIds: ["spices-herbs", "fresh-produce"],
    moqMin: "10",
    moqUnit: "กิโลกรัม/ออเดอร์",
    certificationBody: "CICOT",
    verified: false,
    createdAt: "2025-02-05",
  },
]
